DROP TABLE IF EXISTS PUBLIC.PARTNERMAPPING;
DROP TABLE IF EXISTS PUBLIC.CUSTOMER;

CREATE TABLE PUBLIC.CUSTOMER(
  ID IDENTITY PRIMARY KEY,
  VERSION INT DEFAULT 0 NOT NULL,

  /*nameInfo*/
  FIRSTNAME VARCHAR(40),
  MIDNAME VARCHAR(40),
  LASTNAME VARCHAR(40),

  BALANCE DECIMAL(20, 2) DEFAULT 0.0,

  STATUS VARCHAR(10) NOT NULL,

  /*credentials*/
  LOGIN VARCHAR(40),
  PWDHASH VARCHAR(255)
);

CREATE TABLE PUBLIC.PARTNERMAPPING(
  ID IDENTITY PRIMARY KEY,
  VERSION INT DEFAULT 0 NOT NULL ,

  PARTNERID VARCHAR(120),
  CUSTOMERPARTNERID VARCHAR(120),

  /*nameInfo*/
  FIRSTNAME VARCHAR(40),
  MIDNAME VARCHAR(40),
  LASTNAME VARCHAR(40),

  /*avatar*/
  NAME VARCHAR(255),
  DATA BLOB,

  /*FK to customer*/
  CUSTOMER_ID BIGINT
);

ALTER TABLE PUBLIC.PARTNERMAPPING ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES PUBLIC.CUSTOMER (ID);